services:
  postgres:
    container_name: spring_postgres_container
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: school_db
    ports:
      - "5435:5432"
    restart: unless-stopped